from pathlib import Path
import json
import uuid
from datetime import datetime
import time

ROOT = Path(__file__).parent
QUEUE_DIR = ROOT / 'queue'
OUT_DIR = ROOT / 'out'
PROCESSED_DIR = ROOT / 'processed'

for d in (QUEUE_DIR, OUT_DIR, PROCESSED_DIR):
    d.mkdir(parents=True, exist_ok=True)


def enqueue(requester: str, sharecode: str) -> str:
    """Enqueue a recap job. Returns job id."""
    job_id = uuid.uuid4().hex
    job = {
        'id': job_id,
        'timestamp': datetime.utcnow().isoformat() + 'Z',
        'requester': requester,
        'sharecode': sharecode,
    }
    path = QUEUE_DIR / f'{job_id}.json'
    with path.open('w', encoding='utf-8') as f:
        json.dump(job, f)
    return job_id


def _list_queue_files():
    files = sorted(QUEUE_DIR.glob('*.json'), key=lambda p: p.stat().st_mtime)
    return files


def process_one() -> dict | None:
    """Process a single queued job. Returns result dict or None if none available.

    This is intentionally simple: it creates a placeholder recap_text and writes it
    to OUT_DIR/<jobid>.txt, then moves the job file to processed.
    In future, replace the placeholder step with real processing (download, parse).
    """
    files = _list_queue_files()
    if not files:
        return None
    job_path = files[0]
    try:
        with job_path.open('r', encoding='utf-8') as f:
            job = json.load(f)
    except Exception:
        # if unreadable, move to processed to avoid tight loop
        job_path.replace(PROCESSED_DIR / job_path.name)
        return None

    # Simulate work (fast placeholder)
    share = job.get('sharecode')
    requester = job.get('requester')
    recap_text = f"Recap placeholder for {share}.\n\nThis is autogenerated placeholder text. Replace with real processing."

    out_path = OUT_DIR / f"{job['id']}.txt"
    with out_path.open('w', encoding='utf-8') as f:
        f.write(recap_text)

    # move job to processed
    job_path.replace(PROCESSED_DIR / job_path.name)

    return {'sharecode': share, 'user': requester, 'recap_text': recap_text, 'out_path': str(out_path)}
